language: android

android:
  components:
    - build-tools-20.0.0
    - android-20

install:
  - sudo apt-get install luarocks
  - sudo luarocks make

jdk: oraclejdk7

script:
  - sauce3 new "My Game"
  - sauce3 build desktop
  - sauce3 build android
